Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home2/jmsk62/project/mechanistic_intrep/mechanistic/sae/train_sae.py", line 97, in <module>
    main()
  File "/home2/jmsk62/project/mechanistic_intrep/mechanistic/sae/train_sae.py", line 73, in main
    ds = SAEDataset(acts_dir, layer_key=layer, window_tokens=cfg.get("causal",{}).get("window_tokens",6))
  File "/home2/jmsk62/project/mechanistic_intrep/mechanistic/sae/train_sae.py", line 11, in __init__
    for fn in os.listdir(acts_dir):
FileNotFoundError: [Errno 2] No such file or directory: '${paths.out_root}/acts'
srun: error: gpu2: task 0: Exited with exit code 1
